version: '3'

services:
  boilerplate.api:
    image: boilerplate.api
    build:
      context: ./Boilerplate.API
      dockerfile: Dockerfile
    depends_on:
      - db
  db:
    image: postgres:9.4
    ports:
        - 5432:5432
    environment:
        POSTGRES_PASSWORD: postgres # Default local development credentials
        POSTGRES_USER: postgres
        PGDATA : /var/lib/postgresql/data
    volumes:
      - /opt/postgres:/var/lib/postgresql/data
